In [45]:
import numpy as np

In [65]:
def compute_transitions(x, y, value):    
    # Deslocamento vertical
    if (x == 0):
        T_up    = (0.8 * value[x,y])
        T_down  = (0.8 * value[x+1,y])
        T_left  = (0.1 * value[x,y]) + (0.1 * value[x+1,y])
        T_right = (0.1 * value[x,y]) + (0.1 * value[x+1,y])
    elif (x == 2):
        T_up    = (0.8 * value[x-1,y])
        T_down  = (0.8 * value[x,y])
        T_left  = (0.1 * value[x-1,y]) + (0.1 * value[x,y])
        T_right = (0.1 * value[x-1,y]) + (0.1 * value[x,y])
    else:
        T_up    = (0.8 * value[x-1,y])
        T_down  = (0.8 * value[x+1,y])
        T_left  = (0.1 * value[x-1,y]) + (0.1 * value[x+1,y])
        T_right = (0.1 * value[x-1,y]) + (0.1 * value[x+1,y])
        
    # Deslocamento horizontal
    if (y == 0):
        T_up    += (0.1 * value[x,y]) + (0.1 * value[x,y+1])
        T_down  += (0.1 * value[x,y]) + (0.1 * value[x,y+1])
        T_left  += (0.8 * value[x,y])
        T_right += (0.8 * value[x,y+1])
    elif (y == 3):
        T_up    += (0.1 * value[x,y-1]) + (0.1 * value[x,y])
        T_down  += (0.1 * value[x,y-1]) + (0.1 * value[x,y])
        T_left  += (0.8 * value[x,y-1])
        T_right += (0.8 * value[x,y])
    else:
        T_up    += (0.1 * value[x,y-1]) + (0.1 * value[x,y+1])
        T_down  += (0.1 * value[x,y-1]) + (0.1 * value[x,y+1])
        T_left  += (0.8 * value[x,y-1])
        T_right += (0.8 * value[x,y+1])
    
    # Pega a maior utilidade
    utility = max([T_up, T_down, T_left, T_right])
    
    # Identifica a direção
    if (utility == T_up):
        direction = 'UP'
    elif (utility == T_down):
        direction = 'DW'
    elif (utility == T_left):
        direction = 'LF'
    else:
        direction = 'RG'
    
    return utility, direction

def compute_transitions2(x, y, value):    
    # Deslocamento vertical
    if (x == 0):
        T_up    = (0.8 * value[x,y])
        if (y == 1):
            T_down  = (0.8 * value[x,y])
            T_left  = (0.1 * value[x,y]) + (0.1 * value[x,y])
            T_right = (0.1 * value[x,y]) + (0.1 * value[x,y])
        else:
            T_down  = (0.8 * value[x+1,y])
            T_left  = (0.1 * value[x,y]) + (0.1 * value[x+1,y])
            T_right = (0.1 * value[x,y]) + (0.1 * value[x+1,y])
    elif (x == 2):
        T_down  = (0.8 * value[x,y])
        if (y == 1):
            T_up    = (0.8 * value[x,y])
            T_left  = (0.1 * value[x,y]) + (0.1 * value[x,y])
            T_right = (0.1 * value[x,y]) + (0.1 * value[x,y])
        else:
            T_up    = (0.8 * value[x-1,y])
            T_left  = (0.1 * value[x-1,y]) + (0.1 * value[x,y])
            T_right = (0.1 * value[x-1,y]) + (0.1 * value[x,y])
    else:
        T_up    = (0.8 * value[x-1,y])
        T_down  = (0.8 * value[x+1,y])
        T_left  = (0.1 * value[x-1,y]) + (0.1 * value[x+1,y])
        T_right = (0.1 * value[x-1,y]) + (0.1 * value[x+1,y])
        
    # Deslocamento horizontal
    if (y == 0):
        T_left  += (0.8 * value[x,y])
        if (x == 1):
            T_up    += (0.1 * value[x,y]) + (0.1 * value[x,y])
            T_down  += (0.1 * value[x,y]) + (0.1 * value[x,y])
            T_right += (0.8 * value[x,y])
        else:
            T_up    += (0.1 * value[x,y]) + (0.1 * value[x,y+1])
            T_down  += (0.1 * value[x,y]) + (0.1 * value[x,y+1])
            T_right += (0.8 * value[x,y+1])
    elif (y == 2):
        T_right += (0.8 * value[x,y+1])
        if (x == 1):
            T_up    += (0.1 * value[x,y]) + (0.1 * value[x,y+1])
            T_down  += (0.1 * value[x,y]) + (0.1 * value[x,y+1])
            T_left  += (0.8 * value[x,y])
        else:
            T_up    += (0.1 * value[x,y-1]) + (0.1 * value[x,y+1])
            T_down  += (0.1 * value[x,y-1]) + (0.1 * value[x,y+1])
            T_left  += (0.8 * value[x,y-1])
    elif (y == 3):
        T_up    += (0.1 * value[x,y-1]) + (0.1 * value[x,y])
        T_down  += (0.1 * value[x,y-1]) + (0.1 * value[x,y])
        T_left  += (0.8 * value[x,y-1])
        T_right += (0.8 * value[x,y])
    else:
        T_up    += (0.1 * value[x,y-1]) + (0.1 * value[x,y+1])
        T_down  += (0.1 * value[x,y-1]) + (0.1 * value[x,y+1])
        T_left  += (0.8 * value[x,y-1])
        T_right += (0.8 * value[x,y+1])
    
    # Pega a maior utilidade
    utility = max([T_up, T_down, T_left, T_right])
    
    # Identifica a direção
    if (utility == T_up):
        direction = 'UP'
    elif (utility == T_down):
        direction = 'DW'
    elif (utility == T_left):
        direction = 'LF'
    else:
        direction = 'RG'
    
    return utility, direction

def update_value(rw, value, policy):
    value_tmp = np.array(value)
    policy_tmp = np.array(policy)
    
    # Percorre a matriz e calcula a utilidade de cada posição não terminal
    for index, v in np.ndenumerate(value_tmp):
        if (index == (0,3)) or (index == (1,3)): #or (index == (1,1))):
            continue
        
        # Identifica as posições x e y do estado atual
        x, y = index[0], index[1]
        
        # Calcula a utilidade da melhor transição a partir do estado atual 
        max_transition, direction = compute_transitions(x, y, value_tmp)
        #max_transition, direction = compute_transitions2(x, y, value_tmp)
        
        # Equação de Bellman: U(s) = R(s) + y.max(sum(T(s,a,s').U(s')))
        utility = rw[x,y] + max_transition
        
        # Atualiza a utilidade
        value[x,y] = utility
        
        # Atualiza a política
        policy[x,y] = direction
    
    # Verifica se houve mudança na política
    if np.array_equal(policy, policy_tmp):
        unchanged = True
    else:
        unchanged = False
        
    return value, policy, unchanged

In [135]:
print('Início')
# Definição da matriz de recompensas
r = -0.4
#r = -0.04
#r = -0.0004

rw = np.full((3,4), r)
rw[1,1] = -0.5
rw[2,3] = 0.2
rw[0,3] = 1
rw[1,3] = -1
print('rw = \n' + str(rw))

# Inicialização da matriz de utilidade
value = np.zeros((3,4))
#value = np.ones((3,4))
#value = np.random.random((3,4))

# Ajuste da utilidade dos estados finais
value[0,3] = 1
value[1,3] = -1
print('value = \n' + str(value))

# Inicialização da matriz de política
policy = np.full((3,4), '', dtype=object)

# Ajuste da política dos estados finais
policy[0,3] = '1'
policy[1,3] = '-1'
print('policy = \n' + str(policy))

iteraction = 1
unchanged = False
unchangedCount = 0
# Realiza iterações até encontrar a melhor política para o problema
while (iteraction <= 100):    
    # Atualiza as utilidades
    value, policy, unchanged = update_value(rw, value, policy)
    
    # Após 5 iterações sem atualizar a política, sai do laço
    if unchanged:
        unchangedCount += 1
    else:
        unchangedCount = 0
    if unchangedCount == 10:
        break
        
    iteraction += 1

print('\n## Iteração ' + str(iteraction-1) + ' ##')
print('value = \n' + str(value))
print('policy = \n' + str(policy))
print('Fim')

Início
rw = 
[[-4.e-04 -4.e-04 -4.e-04  1.e+00]
 [-4.e-04 -5.e-01 -4.e-04 -1.e+00]
 [-4.e-04 -4.e-04 -4.e-04  2.e-01]]
value = 
[[ 0.99357033  0.57172543  0.06382933  1.        ]
 [ 0.29625475  0.74431588  0.77020419 -1.        ]
 [ 0.94977033  0.8392432   0.03619189  0.5799892 ]]
policy = 
[['' '' '' '1']
 ['' '' '' '-1']
 ['' '' '' '']]

## Iteração 37 ##
value = 
[[ 5.72380167  5.53191208  5.36954446  1.        ]
 [ 5.9547389   5.65229273  5.70926816 -1.        ]
 [ 6.19921389  6.43642322  6.74080394  7.07605337]]
policy = 
[['DW' 'LF' 'LF' '1']
 ['DW' 'DW' 'DW' '-1']
 ['RG' 'RG' 'RG' 'DW']]
Fim
